"""
@author: weichenglin0215
@title: ComfyUI Flower Tools
@description: Powerful tools for prompt generation and file management in ComfyUI.
"""
from .FlowerMultilinePromptSelector import NODE_CLASS_MAPPINGS as MS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MS_DISPLAY
from .FlowerKeywordReplacer import NODE_CLASS_MAPPINGS as KR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as KR_DISPLAY
from .FlowerListOfStrings import NODE_CLASS_MAPPINGS as LS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LS_DISPLAY
from .FlowerFileNameCombination import NODE_CLASS_MAPPINGS as FC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FC_DISPLAY
from .FlowerTCSCConverter import NODE_CLASS_MAPPINGS as CC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CC_DISPLAY
from .FlowerStringComparison import NODE_CLASS_MAPPINGS as SC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SC_DISPLAY
from .FlowerRemoveCommentedText import NODE_CLASS_MAPPINGS as RC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RC_DISPLAY
from .FlowerSplitSentences import NODE_CLASS_MAPPINGS as SS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SS_DISPLAY

NODE_CLASS_MAPPINGS = {**MS_MAPPINGS, **KR_MAPPINGS, **LS_MAPPINGS, **FC_MAPPINGS, **CC_MAPPINGS, **SC_MAPPINGS, **RC_MAPPINGS, **SS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**MS_DISPLAY, **KR_DISPLAY, **LS_DISPLAY, **FC_DISPLAY, **CC_DISPLAY, **SC_DISPLAY, **RC_DISPLAY, **SS_DISPLAY}

WEB_DIRECTORY = "./web"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
