from .FlowerMultilinePromptSelector import NODE_CLASS_MAPPINGS as MS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MS_DISPLAY
from .FlowerKeywordReplacer import NODE_CLASS_MAPPINGS as KR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as KR_DISPLAY

NODE_CLASS_MAPPINGS = {**MS_MAPPINGS, **KR_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**MS_DISPLAY, **KR_DISPLAY}

WEB_DIRECTORY = "./web"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
