from .FlowerMultilinePromptSelector import NODE_CLASS_MAPPINGS as MS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MS_DISPLAY
from .FlowerKeywordReplacer import NODE_CLASS_MAPPINGS as KR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as KR_DISPLAY
from .FlowerListOfStrings import NODE_CLASS_MAPPINGS as LS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LS_DISPLAY
from .FlowerFileNameCombination import NODE_CLASS_MAPPINGS as FC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FC_DISPLAY
from .FlowerCSTSConverter import NODE_CLASS_MAPPINGS as CC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CC_DISPLAY
from .FlowerStringComparison import NODE_CLASS_MAPPINGS as SC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SC_DISPLAY

NODE_CLASS_MAPPINGS = {**MS_MAPPINGS, **KR_MAPPINGS, **LS_MAPPINGS, **FC_MAPPINGS, **CC_MAPPINGS, **SC_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**MS_DISPLAY, **KR_DISPLAY, **LS_DISPLAY, **FC_DISPLAY, **CC_DISPLAY, **SC_DISPLAY}

WEB_DIRECTORY = "./web"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
